<a href="https://colab.research.google.com/github/zw2497/Twitter_Stream_Processing/blob/master/TopkAppJupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In colab, please uncomment these commands

This installs Apache Spark 2.4.0, Java 8, and Findspark, a library that makes it easy for Python to find Spark.

In [0]:
# !apt-get install openjdk-8-jdk-headless -qq > /dev/null
# !wget -q https://www-us.apache.org/dist/spark/spark-2.4.2/spark-2.4.2-bin-hadoop2.7.tgz
# !tar xf spark-2.4.2-bin-hadoop2.7.tgz
# !pip -q install findspark

# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "./spark-2.4.2-bin-hadoop2.7"

In [0]:
# !pip install -U textblob
# !python -m textblob.download_corpora

# Tweeter Topk 
Top k popular hashtags in two different windows, post sentiment analysis, trend detection

In [0]:
from pyspark.sql.functions import udf, get_json_object, explode, window
from pyspark.sql import SparkSession
from pyspark.sql.types import IntegerType, FloatType
from pyspark.sql.functions import pandas_udf, PandasUDFType

from textblob import TextBlob

from sklearn import linear_model

import pandas as pd
import numpy as np

import time
import os
os.environ["PYSPARK_SUBMIT_ARGS"] = "--master local --packages org.apache.spark:spark-sql-kafka-0-10_2.12:2.4.2 pyspark-shell"

In [0]:
spark = SparkSession \
    .builder \
    .appName("StructuredNetworkWordCount") \
    .getOrCreate()
spark.sparkContext.setLogLevel('FATAL')

In [0]:
df = spark \
  .readStream \
  .format("kafka") \
  .option("kafka.bootstrap.servers", "35.243.144.79:9092") \
  .option("subscribe", "tweepyv1") \
  .option("startingOffsets", "latest") \
  .option("failOnDataLoss", "false") \
  .load()

df.createOrReplaceTempView("raw")
df = spark.sql("""select decode(value, 'utf-8') as value, timestamp 
                  from raw""");

In [0]:
@udf(FloatType())
def senti(x):
    blob = TextBlob(x)
    s = []
    for sentence in blob.sentences:
        s.append(sentence.sentiment.polarity)
    return sum(s)/len(s)

In [0]:
df = df.select('timestamp',\
               get_json_object('value', '$.entities.hashtags[0].text').alias("hashtag"), \
               senti(get_json_object('value', '$.text')).alias("sentiment"))
df = df.filter(df.hashtag.isNotNull())
df.createOrReplaceTempView("datas")

## Trend detection

In [0]:
dftrend = spark.sql("""
select distinct hashtag, count(*) as count_num, avg(sentiment) as sentiment, now() as timestamp
from datas
group by hashtag, window(timestamp, "120 seconds", "30 seconds")
""")

In [0]:
@pandas_udf("key string, value double", PandasUDFType.GROUPED_MAP)  # doctest: +SKIP
def trend_udf(key, pdf):
    reg = linear_model.LinearRegression()
    reg.fit(np.array(pd.to_datetime(pdf.timestamp).astype('int')).reshape(-1,1), np.array(pdf.count_num).reshape(-1,1))
    return pd.DataFrame([key + (reg.coef_[0][0],)])

dftrend = dftrend.groupby('hashtag').apply(trend_udf)

# Top k

In [0]:
dfslow = spark.sql("""
select distinct concat_ws(' ',hashtag, count(*), avg(sentiment)) as value, now() as key
from datas
group by hashtag, window(timestamp, "600 seconds", "120 seconds")
""")

In [0]:
dffast = spark.sql("""
select distinct concat_ws(' ',hashtag, count(*), avg(sentiment)) as value, now() as key
from datas
group by hashtag, window(timestamp, "30 seconds", "5 seconds")
""")

In [0]:
query = dftrend.writeStream.outputMode("complete").queryName("trend").format("memory").option("truncate", "False").start()
query1 = dfslow.writeStream.outputMode("complete").queryName("slow").format("memory").option("truncate", "False").start()
query2 = dffast.writeStream.outputMode("complete").queryName("fast").format("memory").option("truncate", "False").start()

In [0]:
print(query.status)
print(query1.status)
print(query2.status)

{'message': 'Stopped', 'isDataAvailable': False, 'isTriggerActive': False}

In [0]:
res = spark.table("trend").toPandas()
res1 = spark.table("slow").toPandas()
res2 = spark.table("fast").toPandas()

In [0]:
res

                                     key  value
0                                EndGame    0.0
1                          KentuckyDerby    0.0
2                                Germany    0.0
3                   PrudentialCenterROCK    0.0
4                                 deznat    0.0
5                                  ATXWX    0.0
6                                 PeyTen    0.0
7                    USGS303401097374700    0.0
8                                  LACED    0.0
9                               7minutes    0.0
10                           NHLPlayoffs    0.0
11                               dodgers    0.0
12                                pomona    0.0
13                              giveaway    0.0
14                    HerFavoriteHaitian    0.0
15                            NowPlaying    0.0
16                                  US22    0.0
17                     sustainabiliteens    0.0
18                  GarlicAndOilTutorial    0.0
19                            AnuragBasu    0.0
20                               Vermont    0.0
21                             BlueBlood    0.0
22                              RealTime    0.0
23                         PortalsToHell    0.0
24                               WolfCop    0.0
25                                Chiefs    0.0
26                         eattherainbow    0.0
27                            blanlc2019    0.0
28                          USGS08018500    0.0
29                          USGS08181500    0.0
..                                   ...    ...
54                              DoorDash    0.0
55                          USGS08185500    0.0
56                          USGS08020000    0.0
57                            SoundHound    0.0
58                          USGS08178050    0.0
59                               OWL2019    0.0
60                     PieceByMyYoungest    0.0
61                            BlueBloods    0.0
62                          USGS08158700    0.0
63                              Giveaway    0.0
64                       foodphotography    0.0
65                  youknowyourehighwhen    0.0
66                               Houston    0.0
67                           alltogether    0.0
68                       avengersendgame    0.0
69                              Ramyhulu    0.0
70            GiveUstheScarletWitchMovie    0.0
71                        StopCensorship    0.0
72                                  MKOT    0.0
73                               The33rd    0.0
74                    WeLiveTheBeachLife    0.0
75                                livepd    0.0
76                         godswomenrock    0.0
77                               weekend    0.0
78                               Recover    0.0
79                                  TGIF    0.0
80  ExtremelyWickedShockinglyEvilandVile    0.0
81                NJPerformingArtsCenter    0.0
82                  MyTwitterAnniversary    0.0
83                          USGS08178800    0.0

[84 rows x 2 columns]

In [0]:
res1

                                         value                     key
0              TedBundy 1 -0.03750000149011612 2019-05-04 02:26:00.852
1                             SoundHound 1 0.0 2019-05-04 02:26:00.852
2                                  SSNCT 1 0.5 2019-05-04 02:26:00.852
3                        foodphotography 1 0.0 2019-05-04 02:26:00.852
4                                 pomona 1 0.0 2019-05-04 02:26:00.852
5                           BoomerSooner 1 0.0 2019-05-04 02:26:00.852
6                Houston 1 0.06818182021379471 2019-05-04 02:26:00.852
7               RealTime 1 0.10000000149011612 2019-05-04 02:26:00.852
8                               7minutes 1 0.0 2019-05-04 02:26:00.852
9                  goodNIGHTTwitterWorld 1 0.0 2019-05-04 02:26:00.852
10            GiveUstheScarletWitchMovie 1 0.0 2019-05-04 02:26:00.852
11                 WeLiveTheBeachLife 1 0.1875 2019-05-04 02:26:00.852
12                                   AMC 1 0.0 2019-05-04 02:26:00.852
13                                bchs41 1 0.0 2019-05-04 02:26:00.852
14   PrudentialCenterROCK 2 0.3571428656578064 2019-05-04 02:26:00.852
15             BlueBloods 2 0.2429315485060215 2019-05-04 02:26:00.852
16           Travelnurse 1 0.42500001192092896 2019-05-04 02:26:00.852
17              Ramyhulu 1 0.12083332985639572 2019-05-04 02:26:00.852
18                               WolfCop 2 0.0 2019-05-04 02:26:00.852
19                  CNN 1 -0.30000001192092896 2019-05-04 02:26:00.852
20                 Recover 1 0.800000011920929 2019-05-04 02:26:00.852
21              unlucky 1 -0.10000000149011612 2019-05-04 02:26:00.852
22                            NowPlaying 1 0.0 2019-05-04 02:26:00.852
23   youknowyourehighwhen 1 0.4000000059604645 2019-05-04 02:26:00.852
24                      USGS08104500 1 -0.1875 2019-05-04 02:26:00.852
25                JazzFest 1 0.800000011920929 2019-05-04 02:26:00.852
26                LivePD 4 0.11875000153668225 2019-05-04 02:26:00.852
27                         FierceFriday 1 0.25 2019-05-04 02:26:00.852
28               livepd 1 -0.13333334028720856 2019-05-04 02:26:00.852
29         PortalsToHell 1 0.13636364042758942 2019-05-04 02:25:05.889
..                                         ...                     ...
73              DoorDash 1 0.10000000149011612 2019-05-04 02:26:00.852
74        avengersendgame 1 0.1111111119389534 2019-05-04 02:26:00.852
75                 Chiefs 1 0.4000000059604645 2019-05-04 02:26:00.852
76                              lamodels 1 0.0 2019-05-04 02:26:00.852
77      ShowreelShareDay 1 0.46666666865348816 2019-05-04 02:26:00.852
78                PeyTen 2 0.05000000074505806 2019-05-04 02:26:00.852
79        MangledWolfDick 1 0.0416666679084301 2019-05-04 02:26:00.852
80                         godswomenrock 1 0.0 2019-05-04 02:26:00.852
81                          USGS08020000 1 0.0 2019-05-04 02:26:00.852
82                         dogsoftwitter 1 0.0 2019-05-04 02:26:00.852
83                             CARSTour 1 0.25 2019-05-04 02:26:00.852
84                               Germany 1 0.0 2019-05-04 02:26:00.852
85                            BLUEBLOODS 1 0.5 2019-05-04 02:26:00.852
86                           dodgers 1 0.15625 2019-05-04 02:26:00.852
87              ForksUp 1 -0.10000000149011612 2019-05-04 02:26:00.852
88                   RonaldTheThrillHill 1 0.0 2019-05-04 02:26:00.852
89                                 LACED 1 0.5 2019-05-04 02:26:00.852
90                            EndGame 1 0.0625 2019-05-04 02:26:00.852
91                           OWL2019 1 -0.4375 2019-05-04 02:26:00.852
92                 LGBTQ 1 0.14444445073604584 2019-05-04 02:26:00.852
93         PortalsToHell 1 0.13636364042758942 2019-05-04 02:26:00.852
94                     sustainabiliteens 1 0.0 2019-05-04 02:26:00.852
95                          USGS08018500 1 0.0 2019-05-04 02:26:00.852
96                                  US22 2 0.0 2019-05-04 02:26:00.852
97                     PieceByMyYoungest 1 0.0 2019-05-04 02:26:00.852
98                                 ATXWX 1 0.0 2019-05-04 02:26:00.852
99                               weekend 1 0.0 2019-05-04 02:26:00.852
100                             Giveaway 1 0.0 2019-05-04 02:26:00.852
101                           blanlc2019 1 0.0 2019-05-04 02:26:00.852
102               worldfamouscomedystore 1 0.5 2019-05-04 02:26:00.852

[103 rows x 2 columns]

In [0]:
res2

                                         value                     key
0          USGS08178050 1 -0.10000000149011612 2019-05-04 02:25:15.238
1                  goodNIGHTTwitterWorld 1 0.0 2019-05-04 02:25:15.238
2                       USGS08104500 1 -0.1875 2019-05-04 02:25:15.238
3                                Nanaimo 1 0.0 2019-05-04 02:25:15.238
4         KentuckyDerby 1 -0.13333334028720856 2019-05-04 02:25:15.238
5                           USGS08018500 1 0.0 2019-05-04 02:25:15.238
6                            ImpeachBarr 1 0.0 2019-05-04 02:25:15.238
7                                 LivePD 1 0.0 2019-05-04 02:25:15.238
8                             AnuragBasu 1 0.0 2019-05-04 02:25:15.238
9                           USGS08020000 1 0.0 2019-05-04 02:25:15.238
10                  GarlicAndOilTutorial 1 0.0 2019-05-04 02:25:15.238
11         USGS08181500 1 -0.10000000149011612 2019-05-04 02:25:15.238
12                           alltogether 1 0.0 2019-05-04 02:25:15.238
13                                 LACED 1 0.5 2019-05-04 02:25:15.238
14                            blanlc2019 1 0.0 2019-05-04 02:25:15.238
15                             RHFAJobs 1 0.25 2019-05-04 02:25:15.238
16  USGS303401097374700 1 -0.13333334028720856 2019-05-04 02:25:15.238
17         USGS08178800 1 -0.10000000149011612 2019-05-04 02:25:15.238
18                           OWL2019 1 -0.4375 2019-05-04 02:25:15.238
19                                 ATXWX 1 0.0 2019-05-04 02:25:15.238
20         PortalsToHell 1 0.13636364042758942 2019-05-04 02:25:15.238
21         USGS08185500 1 -0.10000000149011612 2019-05-04 02:25:15.238
22                 LGBTQ 1 0.14444445073604584 2019-05-04 02:25:15.238
23                            BLUEBLOODS 1 0.5 2019-05-04 02:25:15.238
24            GiveUstheScarletWitchMovie 1 0.0 2019-05-04 02:25:15.238
25                          USGS08158700 1 0.0 2019-05-04 02:25:15.238

In [0]:
query = dftrend \
  .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)") \
  .writeStream \
  .format("kafka") \
  .outputMode("complete") \
  .option("kafka.bootstrap.servers", "35.243.144.79:9092") \
  .option("topic", "trend") \
  .option("checkpointLocation", "./logtrend") \
  .start()

query1 = dfslow \
  .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)") \
  .writeStream \
  .format("kafka") \
  .outputMode("update") \
  .option("kafka.bootstrap.servers", "35.243.144.79:9092") \
  .option("topic", "slow") \
  .option("checkpointLocation", "./logslow") \
  .start()

query2 = dffast \
  .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)") \
  .writeStream \
  .format("kafka") \
  .outputMode("update") \
  .option("kafka.bootstrap.servers", "35.243.144.79:9092") \
  .option("topic", "fast") \
  .option("checkpointLocation", "./logfast") \
  .start()

In [0]:
query.stop()
query1.stop()
query2.stop()